### ISSUE TITLE
Remove game assets from github repository

### ISSUE THREAD

**Issue by erikiorai** [Peatral/Music-World#1]
Hello I just want it to tell you that hosting a copyrighted assets on github is illegal and com2us may DMCA you or something like that

**Comment by Peatral** [comment]
I wouldn't really worry about this. Yes, the assets are copyrighted material and I know about this. I personally think one can argue in some ways for fair use. Even when not, the Music World IP isn't really big. It is essentially dead, both Music World and World of Tunes were released over a decade ago, and while you can play World of Tunes in an emulator afaik, Music World only runs on legacy LG hardware + software which means if it is not preserved, it will be lost media (which would be a shame). I don't think Com2Us will give me a DMCA Takedown Notice, and if they should, I will happily comply. GitHub explains how DMCA takedowns work more in detail [here](https://docs.github.com/en/site-policy/content-removal-policies/dmca-takedown-policy). As long as I don't receive a takedown notice, I will let this stay public for the sake preservation.
